export const AppConstants = {
	SET_USER: "SET_USER",
	LOG_OUT: "LOG_OUT",
	SET_BLOGS: "SET_BLOGS",
	SET_ACTIVE_BLOG: "SET_ACTIVE_BLOG",
	SET_GALLERY: "SET_GALLERY",
	SET_ACTIVE_GALLERY: "SET_ACTIVE_GALLERY",
	SET_APPLICATIONS: "SET_APPLICATIONS",
	SET_ACTIVE_APPLICATION: "SET_ACTIVE_APPLICATION",
}